[EXTRA_RULES]
ALLOW_WRONG_WAY = 1

[PITS_SPEED_LIMITER]
SPEED_KMH = 160
KEEP_COLLISIONS = 0
DISABLE_WITH_NO_SPEED = 1

[AI_FLOOD]
IGNORE_PITS = 1

; RedLine Souls - Spawn Audio Script (DISABLED - was blocking game audio)
; [SCRIPT_1]
; SCRIPT = """
; DISABLED TO RESTORE NORMAL GAME AUDIO
; """

; Gaulven's teleports for SRP 0.9.3, version 1, Nov 25 2024
; https://discord.gaulven.com/
;

[TELEPORT_DESTINATIONS]
POINT_0= 1
POINT_0_POS= 5049.1,6.9,-4307.9
POINT_0_HEADING= -85.0
POINT_0_GROUP= Belt Inner - Flying Start

POINT_1= 1
POINT_1_POS= 350.6,19.4,-9769.6
POINT_1_HEADING= 49.0
POINT_1_GROUP= C1 Inner - Daikancho Toll Gate

POINT_2= 2
POINT_2_POS= 334.7,19.4,-9771.7
POINT_2_HEADING= 43.0
POINT_2_GROUP= C1 Inner - Daikancho Toll Gate

POINT_3= 1
POINT_3_POS= 1339.6,10.8,-6556.6
POINT_3_HEADING= -54.0
POINT_3_GROUP= C1 Inner - Hamarikyu

POINT_4= 1
POINT_4_POS= 1937.6,13.2,-9727.9
POINT_4_HEADING= 55.0
POINT_4_GROUP= C1 Inner - Kandabashi Junction

POINT_5= 2
POINT_5_POS= 1923.4,13.2,-9731.8
POINT_5_HEADING= 50.0
POINT_5_GROUP= C1 Inner - Kandabashi Junction

POINT_6= 2
POINT_6_POS= 12.9,6.2,-7861.3
POINT_6_HEADING= 85.0
POINT_6_GROUP= C1 Inner - Kasumigaseki Tunnel

POINT_7= 1
POINT_7_POS= 24.6,6.1,-7866.1
POINT_7_HEADING= 94.0
POINT_7_GROUP= C1 Inner - Kasumigaseki Tunnel

POINT_8= 2
POINT_8_POS= 2128.5,-0.3,-7490.2
POINT_8_HEADING= -69.0
POINT_8_GROUP= C1 Inner - Mannen Bridge

POINT_9= 1
POINT_9_POS= 2106.1,-0.3,-7468.0
POINT_9_HEADING= -71.0
POINT_9_GROUP= C1 Inner - Mannen Bridge

POINT_10= 1
POINT_10_POS= 596.2,12.0,-5794.4
POINT_10_HEADING= 228.0
POINT_10_GROUP= C1 Inner - Near Shibaura PA

POINT_11= 2
POINT_11_POS= 609.9,12.0,-5790.8
POINT_11_HEADING= 231.0
POINT_11_GROUP= C1 Inner - Near Shibaura PA

POINT_12= 2
POINT_12_POS= 2505.6,13.0,-9218.4
POINT_12_HEADING= 73.0
POINT_12_GROUP= C1 Inner - Nihonbashi

POINT_13= 1
POINT_13_POS= 2518.0,13.2,-9215.7
POINT_13_HEADING= 62.0
POINT_13_GROUP= C1 Inner - Nihonbashi

POINT_14= 1
POINT_14_POS= -790.4,25.0,-6179.2
POINT_14_HEADING= 192.0
POINT_14_GROUP= C1 Inner - Roppongi

POINT_15= 2
POINT_15_POS= -781.7,23.9,-6163.8
POINT_15_HEADING= 191.0
POINT_15_GROUP= C1 Inner - Roppongi

POINT_16= 2
POINT_16_POS= 2743.1,-0.2,-8675.7
POINT_16_HEADING= -50.0
POINT_16_GROUP= C1 Inner - Shinba Bridge

POINT_17= 1
POINT_17_POS= 2732.5,-0.2,-8654.7
POINT_17_HEADING= -50.0
POINT_17_GROUP= C1 Inner - Shinba Bridge

POINT_18= 1
POINT_18_POS= 376.6,19.0,-9790.9
POINT_18_HEADING= 219.0
POINT_18_GROUP= C1 Outer - Daikancho Toll Gate

POINT_19= 2
POINT_19_POS= 388.6,18.6,-9789.8
POINT_19_HEADING= 201.0
POINT_19_GROUP= C1 Outer - Daikancho Toll Gate

POINT_20= 1
POINT_20_POS= 1369.0,9.8,-6546.5
POINT_20_HEADING= 115.0
POINT_20_GROUP= C1 Outer - Hamarikyu

POINT_21= 1
POINT_21_POS= 1868.7,13.1,-9758.5
POINT_21_HEADING= 231.0
POINT_21_GROUP= C1 Outer - Kandabashi Junction

POINT_22= 2
POINT_22_POS= 1882.1,13.0,-9756.5
POINT_22_HEADING= 235.0
POINT_22_GROUP= C1 Outer - Kandabashi Junction

POINT_23= 1
POINT_23_POS= 13.8,6.2,-7868.9
POINT_23_HEADING= 280.0
POINT_23_GROUP= C1 Outer - Kasumigaseki Tunnel

POINT_24= 2
POINT_24_POS= 23.8,6.0,-7873.9
POINT_24_HEADING= 291.0
POINT_24_GROUP= C1 Outer - Kasumigaseki Tunnel

POINT_25= 1
POINT_25_POS= 2147.6,-0.4,-7470.2
POINT_25_HEADING= 110.0
POINT_25_GROUP= C1 Outer - Mannen Bridge

POINT_26= 2
POINT_26_POS= 2123.1,-0.3,-7446.4
POINT_26_HEADING= 111.0
POINT_26_GROUP= C1 Outer - Mannen Bridge

POINT_27= 1
POINT_27_POS= 701.9,12.1,-5749.2
POINT_27_HEADING= 46.0
POINT_27_GROUP= C1 Outer - Near Shibaura PA

POINT_28= 1
POINT_28_POS= 2512.1,12.2,-9223.3
POINT_28_HEADING= 231.0
POINT_28_GROUP= C1 Outer - Nihonbashi

POINT_29= 2
POINT_29_POS= 2503.3,12.0,-9225.6
POINT_29_HEADING= 232.0
POINT_29_GROUP= C1 Outer - Nihonbashi

POINT_30= 1
POINT_30_POS= -828.6,22.1,-6328.4
POINT_30_HEADING= -36.0
POINT_30_GROUP= C1 Outer - Roppongi

POINT_31= 2
POINT_31_POS= -827.0,22.1,-6341.1
POINT_31_HEADING= -41.0
POINT_31_GROUP= C1 Outer - Roppongi

POINT_32= 1
POINT_32_POS= 2809.1,4.5,-8744.2
POINT_32_HEADING= 130.0
POINT_32_GROUP= C1 Outer - Shinba Bridge

POINT_33= 2
POINT_33_POS= 2795.9,1.9,-8716.4
POINT_33_HEADING= 131.0
POINT_33_GROUP= C1 Outer - Shinba Bridge

POINT_34= 1
POINT_34_POS= -308.6,15.5,6143.8
POINT_34_HEADING= 68.0
POINT_34_GROUP= Daishi PA

POINT_35= 2
POINT_35_POS= -308.5,15.5,6150.7
POINT_35_HEADING= 68.0
POINT_35_GROUP= Daishi PA

POINT_36= 3
POINT_36_POS= -308.1,15.4,6157.9
POINT_36_HEADING= 66.0
POINT_36_GROUP= Daishi PA

POINT_37= 1
POINT_37_POS= -4398.3,29.0,-6324.8
POINT_37_HEADING= -162.0
POINT_37_GROUP= Dogenzaka Parking Lot

POINT_38= 2
POINT_38_POS= -4381.3,29.0,-6304.6
POINT_38_HEADING= -74.0
POINT_38_GROUP= Dogenzaka Parking Lot

POINT_39= 3
POINT_39_POS= -4357.3,29.0,-6323.2
POINT_39_HEADING= 14.0
POINT_39_GROUP= Dogenzaka Parking Lot

POINT_40= 1
POINT_40_POS= -230.1,12.3,1360.0
POINT_40_HEADING= 104.0
POINT_40_GROUP= Heiwajima PA North

POINT_41= 2
POINT_41_POS= -234.9,12.3,1354.1
POINT_41_HEADING= 106.0
POINT_41_GROUP= Heiwajima PA North

POINT_42= 3
POINT_42_POS= -239.8,12.3,1348.1
POINT_42_HEADING= 105.0
POINT_42_GROUP= Heiwajima PA North

POINT_43= 2
POINT_43_POS= -97.7,6.7,1567.8
POINT_43_HEADING= 180.0
POINT_43_GROUP= Heiwajima PA South

POINT_44= 3
POINT_44_POS= -92.7,6.7,1578.5
POINT_44_HEADING= 181.0
POINT_44_GROUP= Heiwajima PA South

POINT_45= 1
POINT_45_POS= -102.9,6.7,1556.1
POINT_45_HEADING= 179.0
POINT_45_GROUP= Heiwajima PA South

POINT_46= 4
POINT_46_POS= -87.1,6.7,1590.5
POINT_46_HEADING= 181.0
POINT_46_GROUP= Heiwajima PA South

POINT_47= 1
POINT_47_POS= 2265.6,45.4,-3718.6
POINT_47_HEADING= -102
POINT_47_GROUP= Route 11 East - Daiba Toll Gate

POINT_48= 1
POINT_48_POS= 2282.9,45.9,-3699.1
POINT_48_HEADING= 81
POINT_48_GROUP= Route 11 West - Daiba Toll Gate

POINT_49= 1
POINT_49_POS= -739.2,32,-7170.4
POINT_49_HEADING= -80
POINT_49_GROUP= Route 3 East - C1 Onramp

POINT_50= 1
POINT_50_POS= -2134.1,37.7,-6479.1
POINT_50_HEADING= -113
POINT_50_GROUP= Route 3 East Takagicho Toll Gate

POINT_51= 1
POINT_51_POS= -2163.2,36.8,-6451.7
POINT_51_HEADING= 61.0
POINT_51_GROUP= Route 3 West Takagicho Toll Gate

POINT_52= 1
POINT_52_POS= -902.4,22.8,-8573.3
POINT_52_HEADING= -67
POINT_52_GROUP= Route 4 East - C1

POINT_53= 1
POINT_53_POS= -4290.3,37.8,-8882.7
POINT_53_HEADING= -146
POINT_53_GROUP= Route 4 East - Yoyogi PA

POINT_54= 1
POINT_54_POS= -911.4,22.9,-8572.9
POINT_54_HEADING= 90
POINT_54_GROUP= Route 4 West - C1

POINT_55= 1
POINT_55_POS= -2187.2,28.8,-8697.3
POINT_55_HEADING= 48
POINT_55_GROUP= Route 4 West - Gaien Exit

POINT_56= 1
POINT_56_POS= 3586.4,20.1,-8822.7
POINT_56_HEADING= 91.0
POINT_56_GROUP= Route 6 West - Hakozaki Junction

POINT_57= 1
POINT_57_POS= 5025.3,22.7,-7941.7
POINT_57_HEADING= 54.0
POINT_57_GROUP= Route 9 North - Kiba Toll Gate

POINT_58= 1
POINT_58_POS= 5978.3,19.2,-5920.1
POINT_58_HEADING= -19.0
POINT_58_GROUP= Route 9 North - Shiomi

POINT_59= 1
POINT_59_POS= 5438.5,24.0,-7242.4
POINT_59_HEADING= -36.0
POINT_59_GROUP= Route 9 North - Southern Kiba

POINT_60= 1
POINT_60_POS= 4023.6,18.4,-8608.0
POINT_60_HEADING= -139.0
POINT_60_GROUP= Route 9 South - Hakozaki Junction

POINT_61= 1
POINT_61_POS= 5128.6,13.5,-7937.6
POINT_61_HEADING= -129.0
POINT_61_GROUP= Route 9 South - Kiba Toll Gate

POINT_62= 1
POINT_62_POS= 5992.4,19.2,-5965.2
POINT_62_HEADING= 165.0
POINT_62_GROUP= Route 9 South - Shiomi

POINT_63= 2
POINT_63_POS= 5471.6,14.0,-7118.4
POINT_63_HEADING= 96.0
POINT_63_GROUP= Route 9 South - Southern Kiba

POINT_64= 1
POINT_64_POS= 5474.5,13.9,-7110.8
POINT_64_HEADING= 80.0
POINT_64_GROUP= Route 9 South - Southern Kiba

POINT_65= 1
POINT_65_POS= -6037.8,46.1,14093.1
POINT_65_HEADING= 302.0
POINT_65_GROUP= Route B North - Daikoku Junction

POINT_66= 1
POINT_66_POS= 1661.8,1.2,3298.4
POINT_66_HEADING= 35.0
POINT_66_GROUP= Route B North - Haneda Airport Tunnel

POINT_67= 1
POINT_67_POS= 1856.8,3.9,10016.6
POINT_67_HEADING= -90.0
POINT_67_GROUP= Route B North - Higashi Toll Gate

POINT_68= 2
POINT_68_POS= 1873.2,3.7,10008.5
POINT_68_HEADING= -91.0
POINT_68_GROUP= Route B North - Higashi Toll Gate

POINT_69= 1
POINT_69_POS= 1095.9,-4.7,-1397.2
POINT_69_HEADING= -77.0
POINT_69_GROUP= Route B North - Hokuburitsu Bridge

POINT_70= 1
POINT_70_POS= -83.8,7.1,10983.1
POINT_70_HEADING= 273.0
POINT_70_GROUP= Route B North - Kawasaki Port

POINT_71= 1
POINT_71_POS= 4103.5,-7.8,8493.0
POINT_71_HEADING= 298.0
POINT_71_GROUP= Route B North - Kawasaki-Ukishima Junction

POINT_72= 1
POINT_72_POS= 905.9,7.2,6.2
POINT_72_HEADING= -23
POINT_72_GROUP= Route B North - Oi-Minami Toll Gate

POINT_73= 2
POINT_73_POS= 905.8,7.3,-14.8
POINT_73_HEADING= -24
POINT_73_GROUP= Route B North - Oi-Minami Toll Gate

POINT_74= 1
POINT_74_POS= 3051.7,0.5,-2988.5
POINT_74_HEADING= -84.0
POINT_74_GROUP= Route B North - Rainbow Bridge Ramp

POINT_75= 1
POINT_75_POS= 2314.4,-1.0,-2452.3
POINT_75_HEADING= 274.0
POINT_75_GROUP= Route B North - Shiokaze Park

POINT_76= 1
POINT_76_POS= 4442.3,2.5,6168.9
POINT_76_HEADING= 3
POINT_76_GROUP= Route B North - Southern Haneda Airport

POINT_77= 1
POINT_77_POS= -5497.1,38.0,13709.7
POINT_77_HEADING= 88.0
POINT_77_GROUP= Route B South - Daikoku Junction

POINT_78= 1
POINT_78_POS= 1637.5,2.3,3284.4
POINT_78_HEADING= -143.0
POINT_78_GROUP= Route B South - Haneda Airport Tunnel

POINT_79= 1
POINT_79_POS= 1148.2,-6.4,-1395.2
POINT_79_HEADING= 110.0
POINT_79_GROUP= Route B South - Hokuburitsu Bridge

POINT_80= 1
POINT_80_POS= -58.0,6.9,11015.7
POINT_80_HEADING= 89.0
POINT_80_GROUP= Route B South - Kawasaki Port

POINT_81= 1
POINT_81_POS= 4048.7,-6.3,8646.2
POINT_81_HEADING= 115.0
POINT_81_GROUP= Route B South - Kawasaki-Ukishima Junction

POINT_82= 1
POINT_82_POS= 3256.9,0.6,4270.1
POINT_82_HEADING= 189.0
POINT_82_GROUP= Route B South - Northern Haneda Airport

POINT_83= 2
POINT_83_POS= 964.9,6.7,-126.1
POINT_83_HEADING= 156.0
POINT_83_GROUP= Route B South - Oi PA

POINT_84= 1
POINT_84_POS= 964.8,6.8,-151.2
POINT_84_HEADING= 156.0
POINT_84_GROUP= Route B South - Oi PA

POINT_85= 1
POINT_85_POS= 3827.5,11.2,-3468.2
POINT_85_HEADING= 100.0
POINT_85_GROUP= Route B South - Rainbow Bridge Ramp

POINT_86= 1
POINT_86_POS= 2357.6,-1.0,-2434.4
POINT_86_HEADING= 106.0
POINT_86_GROUP= Route B South - Shiokaze Park

POINT_87= 1
POINT_87_POS= 4463.9,1.7,6135.0
POINT_87_HEADING= 174.0
POINT_87_GROUP= Route B South - Southern Haneda Airport

POINT_88= 1
POINT_88_POS= 637.7,11.4,-4001.0
POINT_88_HEADING= 328.0
POINT_88_GROUP= Route K1 North - Exit 101/102

POINT_89= 2
POINT_89_POS= -2534.4,11.0,8860.5
POINT_89_HEADING= 268.0
POINT_89_GROUP= Route K1 North - Hamakawasaki Toll Gate

POINT_90= 1
POINT_90_POS= -2547.9,11.1,8865.6
POINT_90_HEADING= 265.0
POINT_90_GROUP= Route K1 North - Hamakawasaki Toll Gate

POINT_91= 1
POINT_91_POS= -9893.7,-7.8,15970.0
POINT_91_HEADING= 29.0
POINT_91_GROUP= Route K1 North - Hanazonobashi Tunnel

POINT_92= 1
POINT_92_POS= 37.2,-0.5,4873.7
POINT_92_HEADING= -42.0
POINT_92_GROUP= Route K1 North - Haneda Ramp

POINT_93= 1
POINT_93_POS= 198.1,6.2,2286.2
POINT_93_HEADING= -5.0
POINT_93_GROUP= Route K1 North - Heiwajima Toll Gate

POINT_94= 1
POINT_94_POS= -4460.6,13.8,10081.6
POINT_94_HEADING= -88.0
POINT_94_GROUP= Route K1 North - Kanseicho

POINT_95= 1
POINT_95_POS= -226.4,10.2,158.4
POINT_95_HEADING= -36.0
POINT_95_GROUP= Route K1 North - Katushima Toll Gate

POINT_96= 1
POINT_96_POS= -10854.3,12.0,13422.8
POINT_96_HEADING= 287.0
POINT_96_GROUP= Route K1 North - Kinko Junction

POINT_97= 1
POINT_97_POS= -8619.4,11.3,11802.7
POINT_97_HEADING= -91.0
POINT_97_GROUP= Route K1 North - Koyasu Toll Gate

POINT_98= 1
POINT_98_POS= 829.7,1.5,4074.5
POINT_98_HEADING= -41.0
POINT_98_GROUP= Route K1 North - Kuko-Nishi Toll Gate

POINT_99= 1
POINT_99_POS= -10627.6,0.9,14823.3
POINT_99_HEADING= 16.0
POINT_99_GROUP= Route K1 North - Minatomirai Toll Gate

POINT_100= 1
POINT_100_POS= -9564.4,11.8,12311.3
POINT_100_HEADING= -69.0
POINT_100_GROUP= Route K1 North - Namamugi Junction

POINT_101= 1
POINT_101_POS= -1336.5,10.5,7907.5
POINT_101_HEADING= -73.0
POINT_101_GROUP= Route K1 North - Rinko

POINT_102= 1
POINT_102_POS= 494.7,5.0,3452.1
POINT_102_HEADING= 12.0
POINT_102_GROUP= Route K1 North - Showajima

POINT_103= 1
POINT_103_POS= 500.7,10.1,-2362.6
POINT_103_HEADING= 3.0
POINT_103_GROUP= Route K1 North - Tennozu Isle

POINT_104= 1
POINT_104_POS= -6404.9,11.9,10869.5
POINT_104_HEADING= 269.0
POINT_104_GROUP= Route K1 North - Tsurumi Bridge

POINT_105= 1
POINT_105_POS= 549.8,12.5,-3790.5
POINT_105_HEADING= 134.0
POINT_105_GROUP= Route K1 South - Exit 101/102

POINT_106= 1
POINT_106_POS= -2532.0,11.0,8865.3
POINT_106_HEADING= 82.0
POINT_106_GROUP= Route K1 South - Hamakawasaki Toll Gate

POINT_107= 2
POINT_107_POS= -2547.5,11.1,8870.7
POINT_107_HEADING= 91.0
POINT_107_GROUP= Route K1 South - Hamakawasaki Toll Gate

POINT_108= 1
POINT_108_POS= -9891.8,-7.8,15962.5
POINT_108_HEADING= -141.0
POINT_108_GROUP= Route K1 South - Hanazonobashi Tunnel

POINT_109= 1
POINT_109_POS= 43.8,-0.6,4853.2
POINT_109_HEADING= 137.0
POINT_109_GROUP= Route K1 South - Haneda Ramp

POINT_110= 1
POINT_110_POS= 215.7,6.1,2253.7
POINT_110_HEADING= 174.0
POINT_110_GROUP= Route K1 South - Heiwajima Toll Gate

POINT_111= 1
POINT_111_POS= -4461.3,13.9,10093.8
POINT_111_HEADING= 93.0
POINT_111_GROUP= Route K1 South - Kanseicho

POINT_112= 1
POINT_112_POS= -204.3,9.5,79.1
POINT_112_HEADING= 142.0
POINT_112_GROUP= Route K1 South - Katushima Toll Gate

POINT_113= 1
POINT_113_POS= -10331.7,19.4,13094.2
POINT_113_HEADING= 119.0
POINT_113_GROUP= Route K1 South - Kinko Junction

POINT_114= 1
POINT_114_POS= -8413.1,10.3,11732.8
POINT_114_HEADING= 81.0
POINT_114_GROUP= Route K1 South - Koyasu Toll Gate

POINT_115= 1
POINT_115_POS= 829.1,5.3,4174.0
POINT_115_HEADING= 134.0
POINT_115_GROUP= Route K1 South - Kuko-Nishi Toll Gate

POINT_116= 1
POINT_116_POS= -10634.3,2.3,14780.3
POINT_116_HEADING= -167.0
POINT_116_GROUP= Route K1 South - Minatomirai Toll Gate

POINT_117= 1
POINT_117_POS= -9732.9,10.9,12550.3
POINT_117_HEADING= 113.0
POINT_117_GROUP= Route K1 South - Namamugi Junction

POINT_118= 1
POINT_118_POS= -1325.8,10.5,7923.5
POINT_118_HEADING= 101.0
POINT_118_GROUP= Route K1 South - Rinko

POINT_119= 1
POINT_119_POS= 500.8,10.0,-2399.5
POINT_119_HEADING= -175.0
POINT_119_GROUP= Route K1 South - Tennozu Isle

POINT_120= 1
POINT_120_POS= -6317.5,12.3,10858.4
POINT_120_HEADING= 83.0
POINT_120_GROUP= Route K1 South - Tsurumi Bridge

POINT_121= 1
POINT_121_POS= -8438.7,18.1,16066.3
POINT_121_HEADING= 87.0
POINT_121_GROUP= Route K3 West - Shin-Yamashita Toll Gate

POINT_122= 1
POINT_122_POS= -6147.9,29.6,13722.3
POINT_122_HEADING= 346.0
POINT_122_GROUP= Route K5 North - Daikoku Junction

POINT_123= 1
POINT_123_POS= 1602.5,13.8,-7977.0
POINT_123_HEADING= 174.0
POINT_123_GROUP= Route Y - Maintenance Area

POINT_124= 2
POINT_124_POS= 1608.7,13.7,-7979.5
POINT_124_HEADING= 174.0
POINT_124_GROUP= Route Y - Maintenance Area

POINT_125= 1
POINT_125_POS= 1202.9,14.8,-7457.0
POINT_125_HEADING= -36.0
POINT_125_GROUP= Route Y - Shimbashi Turn

POINT_126= 1
POINT_126_POS= 1534.0,14.8,-7268.1
POINT_126_HEADING= 4.0
POINT_126_GROUP= Route Y North - Shiodome Toll Gate

POINT_127= 2
POINT_127_POS= 2147.1,-4.2,-8809.6
POINT_127_HEADING= -65.0
POINT_127_GROUP= Route Y North - Tunnel

POINT_128= 1
POINT_128_POS= 2119.8,-4.2,-8753.0
POINT_128_HEADING= -52.0
POINT_128_GROUP= Route Y North - Tunnel

POINT_129= 1
POINT_129_POS= 1434.9,14.9,-7354.5
POINT_129_HEADING= -138.0
POINT_129_GROUP= Route Y South - Shiodome Toll Gate

POINT_130= 1
POINT_130_POS= 2175.8,-6.2,-8799.9
POINT_130_HEADING= 129.0
POINT_130_GROUP= Route Y South - Tunnel

POINT_131= 2
POINT_131_POS= 2157.1,-6.2,-8759.3
POINT_131_HEADING= 111.0
POINT_131_GROUP= Route Y South - Tunnel

POINT_132= 1
POINT_132_POS= 907.0,6.9,1119.3
POINT_132_HEADING= 319.0
POINT_132_GROUP= Routh B North - Ota Stadium

POINT_133= 4
POINT_133_POS= 1099.4,25.3,-4664.9
POINT_133_HEADING= 246.0
POINT_133_GROUP= Shibaura PA

POINT_134= 5
POINT_134_POS= 1099.2,25.3,-4672.4
POINT_134_HEADING= 245.0
POINT_134_GROUP= Shibaura PA

POINT_135= 2
POINT_135_POS= 1098.8,25.3,-4649.8
POINT_135_HEADING= 245.0
POINT_135_GROUP= Shibaura PA

POINT_136= 3
POINT_136_POS= 1098.9,25.3,-4657.4
POINT_136_HEADING= 246.0
POINT_136_GROUP= Shibaura PA

POINT_137= 1
POINT_137_POS= 1098.8,25.3,-4642.1
POINT_137_HEADING= 246.0
POINT_137_GROUP= Shibaura PA

POINT_138= 1
POINT_138_POS= -4052.8,17.8,-6400.1
POINT_138_HEADING= 73.0
POINT_138_GROUP= Shibuya Scramble Crossing

POINT_139= 2
POINT_139_POS= -4051.4,17.8,-6410.7
POINT_139_HEADING= -17.0
POINT_139_GROUP= Shibuya Scramble Crossing

POINT_140= 1
POINT_140_POS= -4093.7,17.5,-6314.0
POINT_140_HEADING= -90.0
POINT_140_GROUP= Shibuya Station Taxi Stand

POINT_141= 2
POINT_141_POS= -4092.0,17.5,-6308.3
POINT_141_HEADING= -91.0
POINT_141_GROUP= Shibuya Station Taxi Stand

POINT_142= 3
POINT_142_POS= -4087.9,17.5,-6303.3
POINT_142_HEADING= 89.0
POINT_142_GROUP= Shibuya Station Taxi Stand

POINT_143= 4
POINT_143_POS= -4085.3,17.5,-6297.3
POINT_143_HEADING= 89.0
POINT_143_GROUP= Shibuya Station Taxi Stand

POINT_144= 1
POINT_144_POS= -4764.2,35.7,-5825.0
POINT_144_HEADING= -36.0
POINT_144_GROUP= Shibuya U-Turn

POINT_145= 2
POINT_145_POS= -4776.9,35.7,-5842.5
POINT_145_HEADING= -23.0
POINT_145_GROUP= Shibuya U-Turn

POINT_146= 3
POINT_146_POS= -4775.1,35.7,-5866.1
POINT_146_HEADING= -109.0
POINT_146_GROUP= Shibuya U-Turn

POINT_147= 1
POINT_147_POS= -4251.7,32.9,-10032.5
POINT_147_HEADING= 208.0
POINT_147_GROUP= Shinjuku Station Taxi Stand

POINT_148= 2
POINT_148_POS= -4268.8,33.0,-9971.6
POINT_148_HEADING= 71.0
POINT_148_GROUP= Shinjuku Station Taxi Stand

POINT_149= East 1
POINT_149_POS= 2107.8,13.7,-8213.5
POINT_149_HEADING= -116.0
POINT_149_GROUP= Shirauobashi Toll Gate

POINT_150= East 2
POINT_150_POS= 2139.9,13.6,-8206.9
POINT_150_HEADING= -136.0
POINT_150_GROUP= Shirauobashi Toll Gate

POINT_151= West 1
POINT_151_POS= 2235.7,14.0,-8144.6
POINT_151_HEADING= 42.0
POINT_151_GROUP= Shirauobashi Toll Gate

POINT_152= West 2
POINT_152_POS= 2202.4,14.0,-8158.8
POINT_152_HEADING= 44.0
POINT_152_GROUP= Shirauobashi Toll Gate

POINT_153= 3
POINT_153_POS= 5838.2,22.4,-4639.6
POINT_153_HEADING= -93.0
POINT_153_GROUP= Tatsumi PA

POINT_154= 4
POINT_154_POS= 5853.3,23.0,-4645.6
POINT_154_HEADING= -92.0
POINT_154_GROUP= Tatsumi PA

POINT_155= 1
POINT_155_POS= 5914.9,24.8,-4650.6
POINT_155_HEADING= 86.0
POINT_155_GROUP= Tatsumi PA

POINT_156= 2
POINT_156_POS= 5895.8,24.2,-4642.9
POINT_156_HEADING= 88.0
POINT_156_GROUP= Tatsumi PA
