<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <SelfContained>false</SelfContained>
        <DebugType>embedded</DebugType>
        <PathMap>$(MSBuildProjectDirectory)=$(MSBuildProjectName)</PathMap>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="../assettoserver-src/AssettoServer.Shared/AssettoServer.Shared.csproj">
          <Private>false</Private>
          <ExcludeAssets>runtime</ExcludeAssets>
      </ProjectReference>
      <ProjectReference Include="../assettoserver-src/AssettoServer/AssettoServer.csproj">
        <Private>false</Private>
        <ExcludeAssets>runtime</ExcludeAssets>
      </ProjectReference>
    </ItemGroup>

</Project>

